// src/web-ui/src/layouts/MainLayout.vue
<script setup lang="ts">
import BackgroundQueryIndicator from "@/layouts/common/BackgroundQueryIndicator.vue";
</script>

<template>
  <div class="min-h-screen grid grid-rows-[auto,auto,1fr,auto]">
    <header>

    </header>
    <BackgroundQueryIndicator />
    <main>
      <router-view />
    </main>
    <footer>

    </footer>
  </div>
</template>

// src/web-ui/src/layouts/MainLayout/index.tsx
import {Suspense} from "react";
import {Outlet} from "react-router-dom";
import {ErrorBoundary} from "react-error-boundary";
import {ErrorBoundaryFallback} from "~/components/ErrorBoundaryFallback.tsx";
import LoadingSpinner from "~/components/LoadingSpinner.tsx";
import NavBar from "./NavBar.tsx";
import Footer from "../common/Footer.tsx";


export default function MainLayout() {
    return <>
        {/* fatal error */}
        <ErrorBoundary FallbackComponent={ErrorBoundaryFallback}>
            <div className="min-h-screen grid grid-rows-[auto,auto,1fr,auto]">
                <NavBar />
                <main className="w-screen">
                    {/* error in requests or so */}
                    <ErrorBoundary FallbackComponent={ErrorBoundaryFallback}>
                        <Suspense fallback={<LoadingSpinner className="h-full" />}>
                            <Outlet />
                        </Suspense>
                    </ErrorBoundary>
                </main>
                <Footer />
            </div>
        </ErrorBoundary>
    </>;
}
