// src/web-ui/src/pages/tags/index.vue
<script setup lang="ts">
import {useMediaQuery} from "@/composables";
import {computed} from "vue";
import type {TagTreeEntry} from "@/pages/tags/types";
import EntryComponent from "@/pages/tags/_EntryComponent.vue";
import {MainLayout} from "@/layouts";

const mediaQuery = useMediaQuery();

const allTags = computed(() => Array.from(new Set(mediaQuery.data?.flatMap(e => e.tags))));

const tagTree = computed(() => {
  if (!allTags.value) return [];
  const entries: TagTreeEntry[] = [];

  for (const tag of allTags.value) {
    let currentEntries: TagTreeEntry[] = entries;
    const parts = tag.split("/");
    for (let i = 0; i < parts.length; i++) {
      const part = parts[i];
      let entry = currentEntries.find(e => e.part === part);
      if (entry === undefined) {
        entry = <TagTreeEntry>{
          part: part,
          tag: parts.slice(0, i+1).join("/"),
          children: []
        };
        const newIndex = currentEntries.findIndex(e => e.part.localeCompare(part) >= 0);
        currentEntries.splice(newIndex === -1 ? currentEntries.length : newIndex, 0, entry);
      }
      currentEntries = entry.children;
    }
  }

  return entries;
});
</script>

<template>
  <MainLayout class="p-2">
    <EntryComponent :tag-entries="tagTree" />
  </MainLayout>
</template>

// src/web-ui/src/pages/media/tags/index.tsx
import useMedia from "~/hooks/useMedia.ts";
import React, {useMemo} from "react";
import SectionHeader from "~/components/Section/Header.tsx";
import TagLink from "~/components/TagLink.tsx";


export default function TagsPage() {
    const { mediaList } = useMedia();

    const tags = useMemo(() => Array.from(new Set(
        mediaList.flatMap(media => media.tags),
    )), [mediaList]);

    const tagTreeList: TreeEntry[] = useMemo(() => {
        const entries: TreeEntry[] = [];

        for (const tag of tags) {
            let currentEntries: TreeEntry[] = entries;
            const parts = tag.split("|");
            for (let i = 0; i < parts.length; i++) {
                const part = parts[i];
                let entry = currentEntries.find(e => e.part == part);
                if (entry === undefined) {
                    entry = {
                        part: part,
                        tag: parts.slice(0, i+1).join("|"),
                        children: [],
                    } as TreeEntry;
                    const newIndex = currentEntries.findIndex(e => e.part.localeCompare(part) >= 0);
                    currentEntries.splice(newIndex === -1 ? currentEntries.length : newIndex, 0, entry);
                }
                currentEntries = entry.children;
            }
        }

        return entries;
    }, [tags]);

    return <>
        <SectionHeader className="px-2">Tags</SectionHeader>
        <div className="p-2">
            <EntryComponent tagEntries={tagTreeList} />
        </div>
    </>;
}


function EntryComponent({tagEntries}: {tagEntries: TreeEntry[]}) {
    return <>
        {tagEntries.map(entry => <React.Fragment key={entry.tag}>
            <TagLink tag={entry.tag} />
            <div className="pl-4">
                <EntryComponent tagEntries={entry.children} />
            </div>
        </React.Fragment>)}
    </>;
}


interface TreeEntry {
    part: string
    tag: string
    children: Array<TreeEntry>
}
