// src/web-ui/src/components/ScrollToMe.tsx
import {useEffect, useRef} from "react";

interface Props {
    if?: boolean
    behavior?: "smooth" | "instant"
}


export default function ScrollToMe(props: Props) {
    const ref = useRef<HTMLDivElement>(null);
    const shouldScroll = props.if !== false;
    const behavior = props.behavior ?? "smooth";

    useEffect(() => {
        if (shouldScroll) {
            ref.current?.scrollIntoView({ behavior });
        }
    }, [shouldScroll, behavior]);

    return <div ref={ref} className="invisible" />;
}

// src/web-ui/src/assets/ScrollToMe.vue
<script setup lang="ts">
import { templateRef } from "@vueuse/core";
import { watch } from "vue";

const props = defineProps<{
  if?: boolean
  behavior?: "smooth" | "instant"
}>();

const element = templateRef<HTMLDivElement>("element");

watch(() => element.value, () => {
  if (element.value && props.if) {
    element.value.scrollIntoView({ behavior: props.behavior });
  }
})
</script>

<template>
  <div v-if="props.if" ref="element" class="invisible" />
</template>
