// src/web-ui/src/layouts/common/BackgroundQueryIndicator.tsx
import {useIsFetching} from "react-query";

export default function BackgroundQueryIndicator() {
    const isFetching = useIsFetching();

    if (!isFetching) {
        return <div className="h-px bg-primary-light" />;
    }

    return <div className="h-px bg-primary-light overflow-hidden">
        <div className="h-px bg-accent-light w-1/3 animate-anything-is-loading" />
    </div>;
}

// src/web-ui/src/layouts/common/_BackgroundQueryIndicator.vue
<script setup lang="ts">
import {useIsFetching, useIsMutating} from "@tanstack/vue-query";

const isFetching = useIsFetching();
const isMutating = useIsMutating();
</script>

<template>
  <div v-if="!(isFetching || isMutating)" class="h-px" />
  <div v-else class="h-px overflow-hidden">
    <div class="h-px bg-primary w-1/3 animate-anything-is-loading" />
  </div>
</template>
