// src/web-ui/src/pages/home/collections.tsx
import {MAXENTRIES} from "~/pages/home/entries.ts";
import useMedia from "~/hooks/useMedia.ts";
import {useMemo} from "react";
import SectionHeader from "~/components/Section/Header.tsx";
import VerticalScrollArea from "~/components/VerticalScrollArea.tsx";
import {Link} from "react-router-dom";
import {encodePath} from "~/util";
import CollectionCard from "~/components/CollectionCard.tsx";


export default function HomepageCollections() {
    const { collections } = useMedia();

    const visible = useMemo(
        () => collections.slice(0, MAXENTRIES),
        [collections],
    );

    if (!visible.length) {
        return null;
    }

    return <>
        <SectionHeader>Collections</SectionHeader>
        <VerticalScrollArea>
            {visible.map(collection => (
                <Link className="hover:scale-105 transition-transform" key={collection.path} to={`/media/collection/${encodePath(collection.path)}`}>
                    <CollectionCard className="h-mixed" collection={collection}/>
                </Link>
            ))}
        </VerticalScrollArea>
    </>;
}

// src/web-ui/src/pages/home/_Collections.vue
<script setup lang="ts">
import type { HomepageElement } from "@/pages/home/elements.ts";
import { Separator } from "@/components/ui/separator";
import SectionHeader from "@/components/composed/SectionHeader.vue";
import { useCollections } from "@/composables/";
import { HorizontalScroll } from "@/components/composed/container";
import CollectionCard from "@/components/composed/mediacard/CollectionCard.vue";

defineProps<{
  element: HomepageElement
}>();

const collections = useCollections();
</script>

<template>
  <template v-if="collections.length">
    <Separator />
    <SectionHeader :to="element.location">
      <component v-if="element.icon" :is="element.icon" />
      Random Collections
    </SectionHeader>
    <HorizontalScroll class="py-2">
      <template v-for="collection in collections" :key="collection.path">
        <router-link :to="{ name: '/media/collection/[...mediaPath]', params: { mediaPath: collection.path } }" class="size-60">
          <CollectionCard :collection="collection" />
        </router-link>
      </template>
    </HorizontalScroll>
  </template>
</template>
