// src/web-ui/src/pages/panel/index.tsx
import {NavLink, Outlet} from "react-router-dom";
import React from "react";


const links = [
    { href: "/panel/settings", label: "Settings" },
    { href: "/panel/problems", label: "Problems" },
    { href: "/panel/stats", label: "Statistics" },
];


export default function ConfigPage() {
    return <>
        <div className="flex flex-col h-full gap-2 p-4 mx-auto max-w-screen-2xl">
            <div className="flex justify-center gap-4 p-2">
                {links.map((link, i) => <React.Fragment key={link.href}>
                    {i !== 0 && <div className="bg-accent/20 w-px h-5 my-auto" />}
                    <NavLink className="group p-1 font-bold [&.active>span]:bg-accent-light [&.active>span]:max-w-full" to={link.href}>
                        {link.label}
                        <span className="block mx-auto max-w-0 group-hover:max-w-full transition-[max-width] h-px bg-accent" />
                    </NavLink>
                </React.Fragment>)}
            </div>
            <Outlet />
        </div>
    </>;
}

// src/web-ui/src/pages/panel.vue
<script setup lang="ts">
import {Separator} from "@/components/ui/separator";
import {MainLayout} from "@/layouts";
import type { RouteLocationRaw } from "vue-router";

interface SubRoute {
  name: string
  location: RouteLocationRaw
}

const subRoutes: SubRoute[] = [
  {
    name: "Settings",
    location: { name: "/panel/settings/" },
  },
  {
    name: "Problems",
    location: { name: "/panel/problems/" },
  },
  {
    name: "Statistics",
    location: { name: "/panel/statistics/" },
  },
];
</script>

<template>
  <MainLayout class="max-w-screen-lg mx-auto p-4 flex flex-col gap-y-4">
    <div class="justify-center flex flex-nowrap gap-x-2 md:gap-x-4">
      <template v-for="(route, index) in subRoutes">
        <Separator v-if="index !== 0" orientation="vertical" class="h-4 my-auto" />
        <router-link :to="route.location" class="group p-1 font-bold" active-class="[&>span]:max-w-full">
          {{ route.name }}
          <span class="block mx-auto max-w-0 group-hover:max-w-full transition-[max-width] h-px bg-primary" />
        </router-link>
      </template>
    </div>
    <router-view />
  </MainLayout>
</template>
