// src/web-ui/src/pages/panel/settings/index.vue
<script setup lang="ts">
import { LucideInfo, LucideLogOut } from "lucide-vue-next";
import { useApiConfigQuery, useWebSettings } from "@/composables";
import {Separator} from "@/components/ui/separator";
import {Button} from "@/components/ui/button";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Setting, SettingDescription, SettingTitle } from "@/components/ui/setting";
import { Switch } from "@/components/ui/switch";

const apiConfig = useApiConfigQuery();
const webSettings = useWebSettings();
</script>

<template>
  <Alert type="warning">
    <LucideInfo class="size-4" />
    <AlertTitle>
      Settings are not synced
    </AlertTitle>
    <AlertDescription class="text-muted-foreground">
      As of now. There exists no system of syncing these settings between devices or browsers.
      This means that everything you configure here will only be applied to this specific browser and device.
    </AlertDescription>
  </Alert>
  <Separator label="Optimization" />
  <Setting>
    <Switch v-model:checked="webSettings.optimizedMedia" />
    <SettingTitle>
      JIT Media Optimization
    </SettingTitle>
    <SettingDescription class="text-muted-foreground">
      The Server allows just-in-time optimization of supported media.
      This reduces the required amount of data that has to be downloaded in exchange for a small decrease in quality of the media.
    </SettingDescription>
  </Setting>
  <div class="grow" />
  <template v-if="apiConfig.data?.requires_auth">
    <Separator />
    <div class="grid place-content-center">
      <router-link :to="{ name: '/auth/logout/' }">
        <Button>
          <LucideLogOut class="inline-block h-5" /> Logout
        </Button>
      </router-link>
    </div>
  </template>
</template>

// src/web-ui/src/pages/panel/settings/index.tsx
import {Link} from "react-router-dom";
import {LogOutIcon} from "lucide-react";
import useApiConfig from "~/hooks/useApiConfig.ts";


export default function ConfigSettingsPage() {
    const apiConfig = useApiConfig();

    return <>
        <h1 className="text-2xl">Settings</h1>
        {apiConfig.allows_optimization && <>
            <div className="px-5 h-px bg-accent/20"/>
            <div className="flex gap-x-2">
                <input type="checkbox" disabled checked className="cursor-not-allowed"/>
                <label>Optimize Content</label>
            </div>
            <p className="text-white/50">
                The Server allows just-in-time optimization of supported media.
                This reduces the required amount of data that has to be downloaded.
            </p>
            <p className="text-white/25">
                (This option currently cannot be disabled)
            </p>
        </>}
        <div className="grow"/>
        {apiConfig.requires_auth && <>
            <div className="px-5 h-px bg-accent/20" />
            <div className="grid place-content-center">
                <Link
                    className="px-2 py-1 bg-white text-black rounded-lg hover:cursor-pointer disabled:cursor-not-allowed" to="/logout">
                    <LogOutIcon className="inline-block h-5" /> Logout
                </Link>
            </div>
        </>}
    </>;
}
